# Sister 19 - Makefile
all: diskimage bootloader kernel

# Recipes
diskimage:
	# TODO : Tambahkan untuk pembuatan image

bootloader:
	# TODO : Tambahkan untuk pembuatan bootloader

kernel:
	# TODO : Tambahkan untuk pembuatan kernel
